<?php

namespace App\Controller;

class CarrinhosController extends AppController {

	public function initialize() {
		parent::initialize(); // TODO: Change the autogenerated stub
		$this->loadModel('Produtos');
	}

	public function index() {
		if (!$this->Carrinho->temItens()) {
			$this->Flash->error("Nenhum item no carrinho!");
			return $this->redirect($this->referer());
		}

		$query = $this->Produtos->find('all')->where(['id IN ' => $this->Carrinho->getItens()]);
		$this->set('produtos', $query);
		$this->set('carrinho', $this->Carrinho->listar());
	}

	public function adicionar($id) {
		$this->Carrinho->adicionar($id, 1);
		return $this->redirect($this->referer()); //volta para pagina que o chamou
	}

	public function remover($id) {
		$this->Carrinho->remover($id, 1);
		return $this->redirect($this->referer());
	}

	public function apagar() {
		$this->Carrinho->apagar();
		return $this->redirect(['controller' => 'produtos', 'action' => 'venda']);
	}

	public function salvarCompra() {

		if (!$this->Carrinho->temItens()) {
			$this->Flash->error("Nenhum item no carrinho!");
			return $this->redirect(['controller' => 'produtos', 'action' => 'venda']);
		}

		$carrinho = $this->Carrinho->listar();
		$itens = $this->Produtos->find('all')->where(['id IN ' => $this->Carrinho->getItens()]);

		$compra = array();
		$compra['user_id'] = $this->Auth->user('id');
		$compra['total'] = 0;


		foreach ($itens as $i => $item) {

			$compra['itens'][$i]['preco'] = $item->preco;
			$compra['itens'][$i]['produto_id'] = $item->id;
			$compra['itens'][$i]['quantidade'] = $carrinho[$item->id];
			$compra['total'] += $item->preco;
		}


		$compra = $this->Carrinhos->newEntity($compra, ['associated' => ['Itens']]);
		if ($this->Carrinhos->save($compra)) {
			$this->Carrinho->apagar();
			$this->Flash->success('Carrinho Salvo com sucesso!');
			return $this->redirect(['controller' => 'produtos', 'action' => 'index']);
		}

		$this->Flash->success('Carrinho nao salvo!');
		return $this->redirect(['action' => 'index']);
	}

	public function buscar() {
		$query = $this->Carrinhos->find('all')->contain(['Itens']);
		$this->set('carrinhos', $query);

		//mostra todos carrinhos cadastrados ---> clique no bolinho para ver
	}

}