<?php

namespace App\Controller;

use Cake\Event\Event;

class ClientesController extends AppController {


	public function initialize() {
		parent::initialize(); // TODO: Change the autogenerated stub

		$this->loadModel('Clientes');
	}

	public function beforeFilter(Event $event) {
		return parent::beforeFilter($event);
		//$this->viewBuilder()->layout('tset')
	}


	public function index() {
		$query = $this->Clientes->find('all');

		$this->set('clientes', $query);
	}

	public function add() {

		if ($this->request->is('post')) {

			$cliente = $this->Clientes->newEntity($this->request->data);
			if ($this->Clientes->save($cliente)) {
				$this->Flash->success('Cliente cadastrado com sucesso!');
				$this->redirect(['action' => 'index']);
			}
		}
	}

}