<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class ComprasTable extends Table {

	public function initialize(array $config) {
		parent::initialize($config); // TODO: Change the autogenerated stub

		$this->belongsTo('Clientes');
		$this->belongsTo('Vendedores');

	}

}